[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
db_filter = ^dtx_.*$
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
http_port = 8069
limit_time_cpu = 600
limit_time_real = 1200
workers = 0
dev_mode = reload,qweb,werkzeug,xml
log_level = debug
log_handler = :DEBUG
admin_passwd = $pbkdf2-sha512$600000$NOYcY6yVUiqltJbS.r835g$hwLECg./r6Sd0LU/2U1UxNimgHmhjH3GjFtgsURKHQ1kEfgkNrlJ9IUGH116WgqBHoJhO6WUoUH.5I7BAfUf3A
list_db = True
max_cron_threads = 1

